name: aurora_fruts
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/fruits.jpg

  fonts:
    - family: SectionIcons
      fonts:
        - asset: assets/fonts/section_menu.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
    - family: DetailsDescriptionIcons
      fonts:
        - asset: assets/fonts/details_description.ttf

    - family: Pacifico-Regular
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
